audio:
  bgm_path: ../../assets/bgm2.wav
  bgm_volume: -20
  fadein_duration: 0
  fadeout_duration: 0  # set to 5000 if you want to fade out 5 seconds before the end of the video
  audio_dir: audio
  dst_audio_path: outputs/dialogue.wav
video:
  height: 1080
  width: 1920
  fps: 30.0
  subtitle_path: outputs/subtitile.ass
  dst_tmp_video_path: outputs/dst_wo_audio.mp4
  layers:
  - type: image
    name: bg
    img_path: ../../assets/bg2.png
    anchor_point:
    - 0
    - 0
    position:
    - 960
    - 540
    scale: 1.0
  - type: slide
    name: slide
    slide_path: slide.pdf
    anchor_point:
    - 0
    - 0
    position:
    - 960
    - 421
    scale: 0.71
  - type: character
    name: zunda
    character_dir: ../../assets/character/zunda
    character_name: zunda
    blink_per_minute: 3
    blink_duration: 0.2
    anchor_point:
    - 0
    - 0
    position:
    - 1779
    - 878
    scale: 0.7
  - type: character
    name: metan
    character_dir: ../../assets/character/metan
    character_name: metan
    blink_per_minute: 3
    blink_duration: 0.2
    anchor_point:
    - 0
    - 0
    position:
    - 79
    - 1037
    scale: 0.7
dst_video_path: outputs/dst.mp4
timeline_path: outputs/timeline.csv
font: Hiragino Maru Gothic Pro
